Implement chrono DateTime<Utc> to / from JS conversion.
DelSkayn/rquickjs pull request #67
Opened 2022-05-31 10:00 UTC by brocaar

This implementation is based on the chrono support as implemented by
https://github.com/theduke/quickjs-rs.

Closes #66.

2022-05-31 10:03 UTC, brocaar commented
@katyo this is my attempt to implement the `DateTime<Utc>` coversion from and to JS. I've also added two tests to validate the conversion.

I've added a new feature `chrono`, to avoid that `chrono` becomes a mandatory dependency of this library.

2022-05-31 12:46 UTC, katyo requested changes

2022-05-31 12:46 UTC, katyo commented on core/Cargo.toml
> +chrono = ["dep:chrono"]
I prefer to avoid using new cargo features here.

2022-05-31 12:46 UTC, katyo commented on core/src/value/convert/from.rs
> +                std::ffi::CStr::from_bytes_with_nul(b"Date\0")
You should use [`CStr::from_bytes_with_nul_unchecked`](https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.from_bytes_with_nul_unchecked) here.
This allows us avoid unnecessary runtime checks.

2022-05-31 12:46 UTC, katyo commented on core/src/value/convert/from.rs
> +        let global = unsafe { crate::qjs::JS_GetGlobalObject(ctx.ctx) };
Use [`Ctx::globals`](https://docs.rs/rquickjs/latest/rquickjs/struct.Ctx.html#method.globals) instead of ffi bindings.

2022-05-31 12:46 UTC, katyo commented on core/src/value/convert/from.rs
> +            crate::qjs::JS_GetPropertyStr(
Use [`Object::get`](https://docs.rs/rquickjs/latest/rquickjs/struct.Object.html#method.get) method to access property by name.

2022-05-31 12:46 UTC, katyo commented on core/src/value/convert/from.rs
> +            unsafe { crate::qjs::JS_IsInstanceOf(ctx.ctx, value.value, date_constructor) > 0 };
Use [`Object::is_instance_of`](https://docs.rs/rquickjs/latest/rquickjs/struct.Object.html#method.is_instance_of) for such checks.

2022-05-31 12:46 UTC, katyo commented on core/src/value/convert/from.rs
> +                crate::qjs::JS_GetPropertyStr(
You shoud get property by name via `Object::get` as a `Function`.
Prefer avoid ffi functions as much as possible.

2022-05-31 12:46 UTC, katyo commented on core/src/value/convert/from.rs
> +                crate::qjs::JS_Call(ctx.ctx, getter, value.value, 0, std::ptr::null_mut())
You can call a `Function` via [`Function::call`](https://docs.rs/rquickjs/latest/rquickjs/struct.Function.html#method.call) like a following:
```rust
getter.call((This(value),))
```
Please, avoid using ffi things directly.

2022-05-31 12:46 UTC, katyo commented on core/src/value/convert/into.rs
> +        let global = unsafe { crate::qjs::JS_GetGlobalObject(ctx.ctx) };
Avoid ffi here.

2022-05-31 12:46 UTC, katyo commented on core/src/value/convert/into.rs
> +            crate::qjs::JS_CallConstructor(
Seems currently we lack equivalent hight-level alternative for `CallConstructor`.
maybe I will add this later.

2022-05-31 13:33 UTC, brocaar commented
Thanks @katyo for reviewing this PR. I'll address your feedback and will push these changes shortly.

2022-05-31 13:48 UTC, brocaar commented
Question:

```rust
    fn from_js(ctx: Ctx<'js>, value: Value<'js>) -> Result<chrono::DateTime<chrono::Utc>> {
        use chrono::TimeZone;

        let value_obj = value.into_object().ok_or(Error::FromJs {
            from: "Date",
            to: "DateTime<Utc>",
            message: None,
        })?;

        let global = ctx.globals();
        let date_constructor: Object = global.get("Date")?;
        let is_date = value_obj.is_instance_of(&date_constructor);

        if is_date {
            let getter: crate::Function = value_obj.get("getTime")?;
            let millis: i64 = getter.call(())?;

            Ok(chrono::Utc.timestamp_millis(millis))
        } else {
            Err(Error::FromJs {
                from: "Date",
                to: "DateTime<Utc>",
                message: None,
            })
        }
    }
```

I think that looks a lot better :-) However, this returns the following error on this line `let millis: i64 = getter.call(())?;`

```text
Exception { message: "not a Date object", file: "", line: -1, stack: "    at getTime (native)\n" }
```

I'll continue debugging this, but if you have any feedback on this, please let me know.

2022-05-31 13:58 UTC, brocaar commented
@katyo the above commit should address all of your feedback points :)

2022-05-31 18:02 UTC, katyo requested changes

2022-05-31 18:02 UTC, katyo commented on core/src/value/convert/from.rs
> +        if is_date {
```rust
    if !value_obj.is_instance_of(&date_constructor) {
        return Err(Error::FromJs {
            from: "Date",
            to: "DateTime<Utc>",
            message: None,
        });
    }

    let getter: crate::Function = value_obj.get("getTime")?;
    let millis: i64 = getter.call((crate::This(value_obj),))?;

    Ok(chrono::Utc.timestamp_millis(millis))
```

2022-05-31 18:02 UTC, katyo commented on core/src/value/convert/into.rs
> +        let timestamp = crate::qjs::JSValue {
Create numeric value via `IntoJs` pls.

2022-05-31 18:02 UTC, katyo commented on core/src/value/convert/into.rs
> +        let mut args = vec![timestamp];
You do not need create vector here.
Simply call constructor like so:
https://github.com/DelSkayn/rquickjs/blob/20b7518a5fa9427e5bdf956a236a692428880cde/core/src/value/typed_array.rs#L162-L167

2022-05-31 18:02 UTC, katyo commented on core/src/value/convert/from.rs
> +        let value_obj = value.into_object().ok_or(Error::FromJs {
Maybe it will be better simply skip `.ok_or` call here because the actual error is `Error::FromJs { from: 'Value', to: 'Object' }`. Your error is misleading.

2022-06-01 10:12 UTC, brocaar commented on core/src/value/convert/from.rs
> +        let value_obj = value.into_object().ok_or(Error::FromJs {
But `into_object() ` returns `Option`, not `Result`. The purpose of the `ok_or()` was to turn this into a `Result` to error in case of `None`.

2022-06-01 10:15 UTC, brocaar commented on core/src/value/convert/from.rs
> +        let value_obj = value.into_object().ok_or(Error::FromJs {
I have updated the error to: `Error::FromJs { from: 'Value', to: 'Object' }`.

2022-06-02 07:43 UTC, katyo commented on core/src/value/convert/from.rs
> +        let value_obj = value.into_object().ok_or(Error::FromJs {
Sure, you can just use `Object::from_value` or even `FromJs::from_js` as alternative for `Value::into_object`.
```rust
let value = Object::from_value(value)?;
let value = Object::from_js(ctx, value)?;
```

2022-06-02 08:59 UTC, brocaar commented on core/src/value/convert/from.rs
> +        let value_obj = value.into_object().ok_or(Error::FromJs {
True, will update this.

2022-06-02 09:03 UTC, brocaar commented
@katyo Your last feedback point with regards to `ok_or(...)` has also been addressed in the last update.

2022-06-03 05:52 UTC, katyo approved these changes

2022-06-03 05:54 UTC, katyo commented
@brocaar LGTM.
Seems CI broken due to problems with cache. Such things sometimes happens with github actions.

2022-06-03 06:21 UTC, merged

2022-06-03 18:42 UTC, katyo commented
@brocaar I added support for `SystemTime` in #68.

2022-06-04 05:47 UTC, katyo commented
@brocaar I made some changes to chrono support (https://github.com/DelSkayn/rquickjs/pull/68/commits/37d0612cbafa5984c2e8396bd2b71d4b62f4c27a).
What do you think about it?

2022-06-06 10:15 UTC, brocaar commented
@katyo looks good to me :+1: